---
- name: disable swap
  command: swapoff -a

 - set_fact:
    kubernetes_node_ip: "{{ hostvars[inventory_hostname]['ansible_'~item]['ipv4']['address'] }}"
  with_items:
    - "{{ kubernetes_common_primary_interface }}"
  when: kubernetes_common_primary_interface is defined

- name: create kubelet config directory
  file:
    dest: /etc/systemd/system/kubelet.service.d
    state: directory

- name: drop extra args kubelet config
  template:
    dest: /etc/systemd/system/kubelet.service.d/09-extra-args.conf
    src: etc/systemd/system/kubelet.service.d/09-extra-args.conf
  notify:
    - restart kubelet
  when: kubernetes_common_primary_interface is defined or kubernetes_common_kubelet_extra_args is defined
